import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import ToastProvider from "@/components/providers/toast-provider";
import { ModalProvider } from "@/components/providers/modal-provider";

// import NextAuthSessionProvider from "@/components/providers/session-provider";
const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
 
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "dark:bg-[#191A19]")}>
      
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ModalProvider/>
            <ToastProvider />
            {children}
          </ThemeProvider>
      
      </body>
    </html>
  );
}
